#**Object-Oriented Programming**

Object-oriented programming (OOP) organizes code into objects, which are instances of classes. These objects can contain both data (attributes) and the functions (methods) that operate on that data. OOP emphasizes the concept of encapsulation, allowing data and methods to be bundled together and interact with each other, making it easier to model and solve complex problems in a more structured and modular way. It also promotes the principles of inheritance and polymorphism, which enable code reuse and flexibility in software design.

In [73]:
int1 = 1947 #Creating one object
print(type(int1))

<class 'int'>

In [74]:
flt1 = 3.1415 #Getting creatted with help of class inheriting all the properties of particular class.
print(type(flt1))

<class 'float'>

In [75]:
class Audi999:
  pass

object1 = Audi999()

In [76]:
print(type(object1))

<class '__main__.Audi999'>

In [77]:
class University_student: #This is class
  def student_info(name): #we can put anything for recordinf info like age, name, etc. This is function or method
    pass

In [78]:
obj1 = University_student()

In [79]:
obj1.student_info()

In [80]:
class Lipstick_Shine:
  def __lipstick__(brand, price, shades, colors, finish):
    pass

In [81]:
obj1 = Lipstick_Shine( )

In [82]:
print(type(obj1))

<class '__main__.Lipstick_Shine'>

In [83]:
class university_student:
  def __int__(self, fname, mname, lname, gender, email, contact):
    pass

In [84]:
obj1 = university_student('Manisha','Maya','Poudel','Female','manishapoudel6@gmail.com', 98765)

TypeError: ignored

In [ ]:
class university_student:
  def __init__(self, fname, mname, lname, gender, email, contact):
    self.fname = fname
    self.mname = mname
    self.lname = lname
    self.gender = gender
    self.email = email
    self.contact = contact

    print(self.fname,  self.mname, self.lname, self.gender,  self.email, self.contact)

In [ ]:
obj1 = university_student('Manisha','Maya','Poudel','Female','manishapoudel6@gmail.com', 98765)

In [ ]:
class Lipstick:
    def __init__(self, brand, price, shades, colors, finish):
        self.brand = brand
        self.price = price
        self.shades = shades
        self.colors = colors
        self.finish = finish

        print(self.brand, self.price, self.shades, self.colors, self.finish)

In [ ]:
obj2 = Lipstick('Shine', 20, 'red velvet', 'red', 'matte' )

In [ ]:
class university_student:
  def __init__(self, fname, mname, lname, gender, email, contact): #init is initalization
    self.fname = fname
    self.mname = mname
    self.lname = lname
    self.gender = gender
    self.email = email
    self.contact = contact
  def stud_details(self): #self is function and self is referring the values from above.
    print(self.fname,  self.mname, self.lname, self.gender,  self.email, self.contact)

In [ ]:
obj1 = university_student('Manisha','Maya','Poudel','Female','manishapoudel6@gmail.com', 98765)

In [ ]:
obj1.stud_details()

In [ ]:
class university_student:
  def __init__(hello, fname, mname, lname, gender, email, contact):

    hello.fname = fname
    hello.mname = mname
    hello.lname = lname
    hello.gender = gender
    hello.email = email
    hello.contact = contact
  def stud_details(hello):
    print(hello.fname,  hello.mname, hello.lname, hello.gender,  hello.email, hello.contact)

In [ ]:
obj1 = university_student('Manisha','Maya','Poudel','Female','manishapoudel6@gmail.com', 98765)

In [ ]:
obj1.stud_details()

In [ ]:
class Smart_phone:
  def __init__(self, color, storage, security, build, processor, camera, price):
    self.color = color
    self.storage = storage
    self.security = security
    self.build = build
    self.processor = processor
    self.camera = camera
    self.price = price

  def phone_details(self):
    print(self.color, self.storage , self.security , self.build , self.processor ,self.camera, self.price )

In [ ]:
obj1 = Smart_phone('Red','125 gb','Secure',2023, 'A16 Bionic','dual',1200)

In [ ]:
obj1.phone_details()

In [ ]:
class transportation:
  pass

In [ ]:
class water(transportation):
  pass

In [ ]:
class land(transportation):
  pass

In [ ]:
class air(transportation):
  pass

In [ ]:
class wheeler2(land):
  pass

In [ ]:
class wheeler4(land):
  pass

![image.png]()

In [ ]:
class Python_Data_Types:
  pass

In [ ]:
class Numeric(Python_Data_Types):
  pass

In [ ]:
class Dictionarya(Python_Data_Types):
  pass

In [ ]:
class Boolean(Python_Data_Types):
  pass

In [ ]:
class Set(Python_Data_Types):
  pass

In [ ]:
class Sequence_Types(Python_Data_Types):
  pass

In [ ]:
class Integer(Numeric):
  pass

In [ ]:
class Complex_Number(Numeric):
  pass

In [ ]:
class Float(Numeric):
  pass

In [ ]:
class Strings(Sequence_Types):
  pass

In [ ]:
class List(Sequence_Types):
  pass

In [ ]:
class Tuple(Sequence_Types):
  pass

***Tuesday August 22, 2023***

In [ ]:
class person:
  def __init__(self, fname, lname): #(fname and lname is parameter)
    self.firstname = fname
    self.lastname = lname


  def printname(self):
    print(self.firstname, ' ', self.lastname)

In [ ]:
obj1 = person('manisha','poudel')

In [ ]:
obj1.printname()

In [ ]:
class childclass(person): #parent class is 'person' we have to put parent class in pranthesis.
# This doesnt have body it clearly inheritant from person class. Child class inheritance
  pass

In [ ]:
obj2 = childclass('Manisha','Poudel')

In [ ]:
obj2.printname() #This printname is also from parent class. Inheriting every properties from parent class.

In [ ]:
class person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname


  def printname(self):
    print('class person',self.firstname, ' ', self.lastname)

In [ ]:
class childclass(person):
  def __init__(self, fname, mname, lname):
    self.firstname = fname
    self.mname = mname
    self.lastname = lname

In [ ]:
obj1 = childclass('Alex','Job','White')

In [ ]:
obj1.printname()

In [ ]:

class House:
  def __init__(self, color, build, bedroom, bathroom):
    self.color = color
    self.build = build
    self.bedroom = bedroom
    self.bathroom = bathroom
  def housedetails(self):
    print('House_Details:',self.color,self.build,self.bedroom,self.bathroom)

In [ ]:
class Bedroom(House):
  def __init__(self, size, bathroom,Fan):
    self.size = size
    self.bathroom = bathroom
    self.fan = Fan
  def bedroomdetails(self):
    print('Bedroom_Details:', self.size, self.bathroom,self.fan)

In [ ]:
obj1 = House('Beige', 2023, 3, 2)

In [ ]:
obj1.housedetails()

In [ ]:
obj = Bedroom(132,'yes','yes')

In [ ]:
obj.bedroomdetails()

In [ ]:
class bathroom(Bedroom):
  def __init__(self, size, shower, bathtub):
    self.size_of_bathrrom = size
    self.shower = shower
    self.bathtub = bathtub

  def bathroom_details(self):
    print('Bathroom_Details:', self.size_of_bathrrom,self.shower, self.bathtub )

In [ ]:
obj2 = bathroom(70, 'Stand Shower','Yes')

In [ ]:
obj2.bathroom_details()

In [ ]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname


  def printname(self):
    print('class person:',self.firstname, ' ', self.lastname)

In [ ]:
class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)

In [ ]:
obj1 = Student('Mayol',"poudel")

In [ ]:
obj1.printname()

In [ ]:
class car:
  def __init__(self, name, model):
    self.name = name
    self.model = model
  def print_details(self):
    print('class car: ', self.name , self.model)

In [ ]:
class audi(car):
  def __init__(self,name,model):
    super().__init__(name, model)

In [ ]:
obj1 = audi('audi 777', 777)

In [ ]:
obj1.print_details()

In [ ]:
class audi(car):
  def __init__(self,name,model,make):
    super().__init__(name, model)
    self.make = 1978

  def print_details(self):
    print(self.name,self.model, self.make)

In [ ]:
obj1 = audi('audi', 777, 1978)

In [ ]:
obj1.print_details()

In [ ]:
class Department_Store():
  def __init__(self, title, est, location):
    self.title_of_store = title
    self.Estsblishment_date = est
    self.location = location

  def store_details(self):
    print(self.title_of_store, self.Estsblishment_date, self.location)

In [ ]:
x = Department_Store('Himalayan', 1997, 'Pokhara')

In [ ]:
x.store_details()

In [ ]:
class Produce(Department_Store):
  def __init__(self,title, est, location, exp, quality, weight ):
    super().__init__(title, est, location)
    self.expiration_date = exp
    self.quality = quality
    self.weight = weight

  def produce_info(self):
    print(self.expiration_date, self.quality, self.weight)

In [ ]:
y = Produce('Himalayan', 1998, 'Pokhara', '29th Aug', 'Organic', '2 pounds')

In [ ]:
y.produce_info()

**Wednesday August 23, 2023**

In [ ]:
#Multiple Inheritance

class mother:
  def __init__(self):
    pass

class father:
  def __init__(self):
    pass

class daughter(mother, father):
  def __init__(self):
    pass

class son(mother, father):
  def __init__(self):
    pass

In [ ]:
class car:
  def __init__(self, color, engine):
    self.color = color
    self.engine = engine

  def car_details(self):
    print('Car Details:', self.color, self.engine)


class bus:
  def __init__(self, color, engine):
    self.color = color
    self.engine = engine

  def bus_details(self):
    print('Bus Details:', self.color, self.engine)

class vehicle(car,bus):
  def __init__(self, color, engine):
    self.color = color
    self.engine = engine

  def vehicle_details(self):
    print('Vehicle Details:',self.color, self.engine)

In [ ]:
x = car('Red','hybrid')

In [ ]:
x.car_details()

In [ ]:
y=bus('Green','motor')

In [ ]:
y.bus_details()

In [ ]:
z = vehicle('White','gasoline')

In [ ]:
z.vehicle_details()

In [ ]:
class a:
  a1 = 'hello'
  def __init__(self):
    self.a2 = "world"
    self.a1 = "hello"
    self.tmp1 = "how"

class b(a):
  b1 = "Where "
  def __init__(self):

    self.b2 = "When"
    self.a1 = "hello"
    self.tmp1 = "how"
    super().__init__()

In [ ]:
obj_a = a()
obj_b = b()

print(obj_a.a1)
print(obj_a.tmp1)
print(obj_b.a1)
print(obj_b.a2)
print(obj_b.b1)
print(obj_b.b2)
print(obj_b.tmp1)

In [ ]:
class a:
  var_a1 = "This is my first print statement inside class a "
  def __init__(self):
    self.var_a2 = "This my second print statement inside function __init__ of class a"
    self.var_a1 = "Instance variable in class a"
    self.var_tmp1 = "This is var_tmp1 inside class a"

class b(a):
  var_b1 = "this is my third print statement inside class b "
  def __init__(self):
    super().__init__()
    self.var_b2 = "This is my fouth print statement inside function __init__ of class b"
    self.var_a1 = "Instance variable in class b"
    self.var_tmp1 = "This is var_tmp1 inside class b"

In [ ]:
obj_a = a()
obj_b = b()

print(obj_a.var_a1)
print(obj_a.var_tmp1)
print(obj_b.var_a1)
print(obj_b.var_a2)
print(obj_b.var_b1)
print(obj_b.var_b2)
print(obj_b.var_tmp1)

In [ ]:
class School:
  variable1 = 'There are plenty classrooms'
  def __init__(self):
    self.variable2 = 'Students are from diff background'
    self.variable3 = 'Teachers are happy with wages'
    self.variable4 = 'Friendly Environment'

class Student(School):
  variable5 = 'First variable of class Student'
  def __init__(self):
    self.variable6 = 'Name of the Student'
    self.variable4 = 'Friendly Environment for'
    self.variable2 = 'Students are from diff background'
    super().__init__()

In [ ]:
x = School()

In [ ]:
y = Student()

In [ ]:
print(x.variable1)

In [ ]:
print(x.variable2)

In [ ]:
print(x.variable3)

In [ ]:
print(x.variable4)

In [ ]:
print(y.variable5)

In [ ]:
print(y.variable6)

In [ ]:
print(y.variable4)

In [ ]:
print(y.variable2)

In [ ]:
class Animal:
    def make_sound(self):
        print("Any animal sound")

class Dog(Animal):
    def make_sound(self):
        print("Whoof!")

class Cat(Animal):
    def make_sound(self):
        print("Meow!")

In [ ]:
x = Animal()

In [ ]:
x.make_sound()

In [ ]:
y= Dog()

In [ ]:
y.make_sound()

In [ ]:
z= Cat()

In [ ]:
z.make_sound()

**Thursday August 24, 2023**

1. Over Loading
2. Over Ridding
3. Operator Over Loading
4. Polymorphism
5. Encapsulation

In [ ]:
l = 'Python Programming'

print(len(l))

l = [12,23,34,45,56,67,78,89,90]

print(len(l))

l = (11,22,33,44,55,66,77,88,99,110)

print(len(l))

l = {'a': 'apple',
     'b': 'banana',
     'c': 'cat'}
print(len(l))

In [ ]:
class person:
  def __init__(self, fname, mname, lname):
    pass

  def print_details(self):
    print(self.fname,self.mname,self.lname)

class student(person):
  def __init__(self, fname, mname, lname):
    pass

  def print_details(self):
    print(self.fname,self.mname,self.lname)

In [ ]:
class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car class
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat class
plane1 = Plane("Boeing", "747")     #Create a Plane class

for x in (car1, boat1, plane1):
  x.move()

In [ ]:
class vehicle:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print('move!!')

class Car(vehicle):
  def move(self):
    print("Drive!")

class Boat(vehicle):
  def move(self):
    print("Sail!")

class Plane(vehicle):
  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car class
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat class
plane1 = Plane("Boeing", "747")     #Create a Plane class

for i in (car1,boat1,plane1):
  print(i.brand)
  print(i.model)
  i.move()

In [ ]:
class Animals:
  def __init__(self, name, habitat):
    self.name = name
    self.habitat = habitat

  def animals_detail(self):
    print("This is {self.name} and they live in {self.habitat}")


class Amphibians(Animals):
  def animals_detail(self):
    print('They can live in both land and water')

class Arriels(Animals):
  def animals_detail(self):
    print('They fly')

class Aquatics(Animals):
  def animals_detail(self):
    print('They live in water')


Amphibian = Amphibians('Crocodile','Land and Water') #I've created an object for this three child classes
Arriel = Arriels('Eagle','Air')
Aquatic = Aquatics('Whale', 'Water')

for k in (Amphibian, Arriel, Aquatic):
  print(k.name)
  print(k.habitat)
  k.animals_detail()

***Friday 25Th August***

**Encapsulation**

Encapsulation is used to restrict access to methods and variables. In encapsulation, code and data are wrapped together within a single unit from being modified by accident. Encapsulation is a mechanism of wrapping the data (variables) and code acting on the data (methods) together as a single unit.

In [85]:
#Encapsulation

class transport:

  def __init__(self, brand, model, year):
    self.brandofvehicle = brand
    self.modelofvehicle = model
    self.yearofmfg= year

  def print_details(self):
    print(self.brandofvehicle, self.modelofvehicle, self.yearofmfg)

In [86]:
obj1 = transport('Hyundai','Tucson', 2023)

In [87]:
obj1.print_details()

Hyundai Tucson 2023

In [88]:
class flowers:

  def __init__(self, name, color):
    self.name = name
    self.color = color

  def flower_details(self):
    print(self.name, self.color)

class Rose(flowers):
  def __init__(self, name, color, bloom):
    super().__init__(self, name, color)
    self.bloom = bloom

  def flower_details(self):
    print('Rose is blooming with a lovely fragrance."')

class Sunflower(flowers):
  def __init__(self, name, color, bloom):
    super().__init__(self, name, color)
    self.bloom = bloom
  def flower_details(self):
        print("A sunflower is turning towards the sun.")

In [89]:
obj1 = flowers('Lilly','White')
obj2 = Rose('Rose','Red','Blooming')
obj3 = Sunflower('Sunflower', 'Yellow','Blooming' )

TypeError: ignored

#**Exception Handling**
  1. Build-in Exception
  2. User Define Exception

In [ ]:
#Universal exception
# always use universal exception in the bottom of the file or code.
#if family exception error is there it will go to parent class not to the child
f = open('mytextfile', 'w') #universal exception going to handle any of the error
try:
  # f = open('myTextFile.txt', 'r')
  a = 10/0

except FileNotFoundError as fnfe:
  print('FileNotFoundError ', fnfe)
except ZeroDivisionError as zde:
  print('ZeroDivisionError ', zde)
except ArithmeticError as ae:
  print('ArithmeticError ', ae)
except Exception as e:
  print('Exception ', e)

In [ ]:
a= [1,2,3,4,5]
 print(a)

In [ ]:
try:
 a= [1,2,3,4,5]
 print(a)

except IndentationError as ie:
  print('IndentationError',ie)

In [ ]:
f = open('mytextfile', 'w')

In [ ]:
f = write('mytextfile','r')

In [ ]:
try:
  f = write('mytextfile','r')

except NameError as ne:
  print('NameError',ne)
except Exception as e:
  print('Exception ', e)

In [ ]:
result = 2/0

In [ ]:
try:

  result = 2/0
except ZeroDivisionError as zde:
  print('ZeroDivisionError', zde)

In [ ]:
try:
  result = 2/0
except ArithmeticError as ae:
  print('ArithmeticError',ae)

In [ ]:
a =int(input('Enter the number'))

In [ ]:
try:
  a =int(input('Enter the number'))
except ValueError as ve:
  print('ValueError', ve)

In [ ]:
try:
  a =int(input('Enter the number'))
except Exception as e:
  print('Exception', e)

In [ ]:
class user_define_exception1(Exception):
  pass

In [ ]:
try:
  print('my first user define exceptopm',12/0)
except user_define_exception1 as ude1:
  print('user_define_exception1', ude1)
except Exception as e:
  print('Exception ', e)

In [ ]:
class AgeOfVoting(Exception): # It is declaring the voting.
  "Raise when the input is less than 18"
  pass

number = 18

try:
  input_num = int(input('Enter Age '))
  if input_num < 18:
    raise AgeOfVoting #raise allows to raise the exception
  else:
    print('Eligible for voting ')

except AgeOfVoting as aov:
  print('exception as Invalid Age')

In [ ]:
class AgeOfVoting(Exception):

input_num = int(input('Enter Age '))
if input_num < 18:
  raise AgeOfVoting #raise allows to raise the exception
else:
  print('Eligible for voting ')

In [ ]:
value = int(input('Number Please:- '))
if value < 0:
  raise CustomError("Value cannot be negative")
else:
  print("Value is positive ")

In [ ]:
class CustomError(Exception):
    pass
value = int(input('Number Please:- '))
try:
    if value < 0:
      raise CustomError("Value cannot be negative")
    else:
      print("Value is positive ")

except CustomError as e:
    print(e)

#**Numpy Library**

NumPy library" is a fundamental library in the Python programming language used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

In [ ]:
v = np.zeros(10)
print(v)

In [ ]:
print('%d bytes' %(v.size * v.itemsize)) #above output is taking 8 bytes on each item

In [ ]:
%run ('python -c import numpy; numpy.info(numpy.add)')

In [ ]:
v = np.zeros(10)
v[4] = 1
print(v)

In [ ]:
v = np.arange(10,20)
print(v)

In [ ]:
v = np.arange(10,50) #in numpy we call list of the number a vector
print(v)
print(type(v)) #ndarray is ndimensional array

In [ ]:
v = np.arange(50)
print(v)
v = v[::-1]
print(v)

In [ ]:
num = [1, 2, 3, 4, 5]
arange = np.array(num)

print("Original array:", arange)

squared_arange = arange ** 2
sum_of_arange = np.sum(arange)
mean_of_arange = np.mean(arange)

print("Squared array:", squared_arange)
print("Sum of array elements:", sum_of_arange)
print("Mean of array elements:", mean_of_arange)

In [ ]:
v = np.arange(9).reshape(3,3)
print(v)

In [ ]:
nz = np.nonzero([1,0,0,2,0,0,3,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,6])
print(nz)

In [ ]:
v = np.eye(3)
print(v)

In [ ]:
v = np.eye(5)
print(v)

In [ ]:
#np is numpy
#random1 is function
#random is class

v = np.random.random(10)
print(v)

In [ ]:
v = np.random.random((10,10)) #2 dimensional value
print(v)

In [ ]:
v = np.random.random((2,3,4)) #3 dimensional value
print(v)

In [ ]:
v = np.random.random((1,3))
print(v)

In [ ]:
random_range = np.random.random(5) * 10 + 10
print(random_range)

In [ ]:
v = np.random.random((10,10)) #RAndom values always give the new value every time we run
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

In [ ]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)

In [ ]:

v = np.ones((10,10))
print(v)
v[1:-1,1:-1] = 0
print(v)

In [ ]:
v = np.zeros((10,10))
v[1:-1, 1:-1] = 1
print(v)

In [ ]:
v = np.ones((5,5))
print(v)
v = np.pad(v, pad_width =1, mode = 'constant', constant_values= 0)
print(v)

In [ ]:
#nan means nothing
#don't compare nan with zero '0'

np.nan

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

In [ ]:
print(0 + np.nan)
print(np.nan + np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

In [ ]:
print(np.nan > np.nan)

In [ ]:
print(1 - np.nan)

In [ ]:
print(1 * 0.3)

In [ ]:
3 * 0.1

In [ ]:
print(1/ np.nan)
print(np.nan + np.nan)
print(np.nan == np.nan)
print(np.nan - np.nan)
print(np.nan * 0)
print(2 - np.nan)
print(np.nan != np.nan)

In [ ]:
v = np.nan
nan = np.isnan(v)
print(nan)

In [ ]:
v = np.ones((5,5))
print(v)
v = np.diag([1, 2, 3, 4])
print(v)

In [ ]:

v = np.ones((5,5))
for i in range(1, v[0]):
  v[i, :i] = [1, 2, 3, 4][:i]

print(v)

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

In [ ]:
x = 10
y = 5
print(x / y)

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
import numpy as np

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

In [ ]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

In [ ]:
# Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

In [ ]:
# Normalize a 5x5 random matrix

Z = np.random.random((5,5))
print(Z)
Zmax, Zmin = Z.max(), Z.min()
print(Zmax)
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

In [ ]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [ ]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15]])

B = np.array([[2, 0],
              [1, 3],
              [4, 5]])

Z = np.dot(A, B)
print(Z)

In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

In [ ]:
# What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
# What are the result of the following expressions?

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

In [ ]:
# How to round away from zero a float array ?

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

In [ ]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

In [ ]:
# Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
import numpy as np

sqrt_value = np.sqrt(9)
print(sqrt_value)


emath_sqrt_value = np.emath.sqrt(9)
print(emath_sqrt_value)


complex_sqrt = np.sqrt(-4)
print(complex_sqrt)

complex_emath_sqrt = np.emath.sqrt(-4)
print(complex_emath_sqrt)


emath_high_precision = np.emath.sqrt(2)
print(emath_high_precision)

In [ ]:
# How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('yesterday:',yesterday, 'today:',today, 'tomorrow:',tomorrow)

In [ ]:
# How to get all the dates corresponding to the month of July 2016?

Z = np.arange('2023-07', '2023-08', dtype='datetime64[D]')
print(Z)

In [ ]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

In [ ]:
# Extract the integer part of a random array using 5 different methods?

Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

In [ ]:
# Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

In [ ]:
# Create a random vector of size 10 and sort it

Z = np.random.random(10)
Z.sort()
print(Z)

In [ ]:
# How to sum a small array faster than np.sum?

Z = np.arange(10)
np.add.reduce(Z)

In [ ]:
# Consider two random array A and B, check if they are equal?

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A, B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

In [ ]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates?

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

In [ ]:
# Create random vector of size 10 and replace the maximum value by 0?

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

In [ ]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area?

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

In [ ]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))?

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

In [ ]:
# Print the minimum and maximum representable value for each numpy scalar type?

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

In [ ]:
# How to find the closest value (to a given scalar) in a vector?

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

In [ ]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?

Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

In [ ]:
# What is the equivalent of enumerate for numpy arrays?

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

In [ ]:
# How to sort an array by the nth column?

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

In [ ]:
# Find the nearest value from a given value in an array?

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

In [ ]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

In [ ]:
import numpy as np
lst1 = [11,22,33,44,55,66,77]
arr1 = np.array(lst1)
print(type(arr1))

In [ ]:
tup1 = (12,23,34,45,56,67,78,89)
arr2 = np.array(tup1)
print(type(arr2))

In [ ]:
set = {1,2,3,4,0,'t','d','apple',True, False, 'Programming'}
arr3 = np.array(set)
arr3

In [ ]:
dic1 = {'a':[1,2,3,4,0], 'b':['apple'], 'c':(True, False), 'd':'Programming'}
arr4 = np.array(dic1)
arr4

In [ ]:
str1 = 'Python Programming'
arr5 = np.array(str1)
print(arr5)

In [ ]:
str = "Apple"
arr = np.array(str)
print(arr)

In [ ]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1d)
arr1d.ndim

In [ ]:
arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2d)
arr2d.ndim

In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d)
arr3d.ndim

In [ ]:
x = np.array([[[22,33,44],[2,3,4],[0,4,66]]])
print(x)
x.ndim

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #collection of 2 dimensional is 3 dimensional
e = np.array([
    [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
    [[[11, 12, 13], [14, 15, 16]], [[11, 12, 13], [14, 15, 16]]] #two set of 4th dimensional
    ])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#**Panda Library**
Wednesday August 30, 2023

The "Pandas" library in Python is a powerful and widely used library for data manipulation and analysis. It provides easy-to-use data structures and functions to work with structured data, such as spreadsheets or SQL tables. Pandas is often used in data science, data analysis, and data preprocessing tasks.

In [ ]:
!pip install pandas

In [ ]:
!pip install LightGBM

In [ ]:
!pip install numpy

In [ ]:
!pip install pytorch

In [ ]:
import pandas as pd #rich collection of stuff

# https://pandas.pydata.org/

In [ ]:
path = '/content/Churn_Modelling.csv'
df = pd.read_csv(path) #df = dataframe using path and csv stands for comma seperated value
df                     #data provided in csv format

In [ ]:
path = "/content/Churn_Modelling.csv"
df_Churn_Modelling_csv = pd.read_csv(path)
df_Churn_Modelling_csv

In [ ]:
!pip install xlwt

In [ ]:
import xlwt

In [ ]:
#Converting data into different format
df_Churn_Modelling_csv.to_excel("df_Churn_Modelling_xls.xls")

In [ ]:
df_Churn_Modelling_csv.to_excel("df_Churn_Modelling_xlsx.xlsx")

In [ ]:
df_Churn_Modelling_csv.to_html("df_Churn_Modelling_html.html")

In [ ]:
df_Churn_Modelling_csv.to_json("df_Churn_Modelling_json.json")

In [ ]:
df_Churn_Modelling_csv.to_xml("df_Churn_Modelling_xml.xml")

In [ ]:
df_Churn_Modelling_csv.to_string("df_Churn_Modelling_string.string")

In [ ]:
path_html = "/content/df_Churn_Modelling_html.html"
Churn_Modelling_html = pd.read_html(path_html)
Churn_Modelling_html

In [ ]:
path = "/content/df_Churn_Modelling_json.json"
Churn_Modelling_json = pd.read_json(path)
Churn_Modelling_json

In [ ]:
path = "/content/df_Churn_Modelling_xml.xml"
Churn_Modelling_xml = pd.read_xml(path)
Churn_Modelling_xml

In [ ]:
path = "/content/df_Churn_Modelling_xlsx.xlsx"
Churn_Modelling_xlsx = pd.read_excel(path)
Churn_Modelling_xlsx

In [ ]:
path = "/content/df_Churn_Modelling_xls.xls"
Churn_Modelling_xls = pd.read_excel(path)
Churn_Modelling_xls

In [ ]:
path = "/content/df_Churn_Modelling_string.string"
Churn_Modelling_string = pd.read_csv(path)
Churn_Modelling_string

**Components of Python Pandas**
1. series - one dimensional data
2. Datframe - muti diemensional data

In [90]:
import pandas as pd

In [91]:
list1 = [12,23,34,45,56,78,89,90,110]
sr1 = pd.Series(list1)
sr1, sr1.ndim

(0     12
 1     23
 2     34
 3     45
 4     56
 5     78
 6     89
 7     90
 8    110
 dtype: int64,
 1)

In [ ]:
tup1 = ('a',[5,3,4],1,4,5,'apple') #ordered sequence can be rearrange
sr2 = pd.Series(tup1)
sr2

In [ ]:
set1 = {'a','n','python',9,2,1,-1,-4,'programming'} #in unordered we cannot have any index on it.
sr3 = pd.Series(set1)
sr3

In [ ]:
dict1 = {'a':'apple','b':'buss','c':[1,2,3]}
sr4 = pd.Series(dict1)
sr4

In [ ]:
import pandas as pd

lst1 = [12,23,34,45,56,67,78,89,90,110]
sr1 = pd.Series(lst1)
sr1, len(sr1), sr1.count(), sr1.ndim, type(sr1), sr1.size, sr1.dtype, sr1.item, sr1.items, sr1.nbytes, sr1.shape

**Fiday Sep 1st 2023**

In [ ]:
import numpy as np #PAnda is upon numpy
import pandas as pd

#**Python Pandas Data frame**

COllection of multiple vectors,matrix,dimensional,etc

In [92]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
list1 = [12,23,34,45,56,67,78,89,90,110]
df1 = pd.DataFrame(list1)
print(df1)
type(df1)

In [ ]:
lang = ['C','C++','Java','Python']
df2 =pd.DataFrame(lang)
df2

In [ ]:
rating = [4,3,2,1]
df2[1] = rating
df2

In [ ]:
df2.columns = ['langauge', 'rating']
df2

In [ ]:
tup1 = (1,2,3,4,5,'a','b','c','d')
df3 = pd.DataFrame(tup1)
df3

In [ ]:
rank = ('A','B','C','D','E','F','G','H','I')
df3[1]= rank
df3

In [ ]:
df3.columns = ['Numbers', 'Rank']
df3

In [ ]:
# Create Dataframe from Dictionary
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b'])
df4 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b' ,'c'])
df5 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b' ,'c' , 'd'])

In [ ]:
df2

In [ ]:
df3

In [ ]:
df4

In [ ]:
df5

In [ ]:
df6 = pd.DataFrame({'ID':[1,2,3,4], 'Name':['Ramesh','Suresh','Naresh','Sukesh']})
df6

In [ ]:
df6['ID'], df6['Name']

In [ ]:
dict1 = {'A': pd.Series([1,2,3,4], index = ['a','b','c','d']), #Index is for rows
         'B': pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
         }
df1 = pd.DataFrame(dict1)
df1

In [ ]:
#Deleting the column
del df1['B']
df1

#**Dataframe of Random Numbers with Date Indices**

In [124]:
import pandas as pd

In [125]:
import numpy as np

In [126]:
dates = pd.date_range(start='01-Aug-2023', end='31-Aug-2023')

In [127]:
dates

DatetimeIndex(['2023-08-01', '2023-08-02', '2023-08-03', '2023-08-04',
               '2023-08-05', '2023-08-06', '2023-08-07', '2023-08-08',
               '2023-08-09', '2023-08-10', '2023-08-11', '2023-08-12',
               '2023-08-13', '2023-08-14', '2023-08-15', '2023-08-16',
               '2023-08-17', '2023-08-18', '2023-08-19', '2023-08-20',
               '2023-08-21', '2023-08-22', '2023-08-23', '2023-08-24',
               '2023-08-25', '2023-08-26', '2023-08-27', '2023-08-28',
               '2023-08-29', '2023-08-30', '2023-08-31'],
              dtype='datetime64[ns]', freq='D')

In [128]:
dates = pd.date_range('today', periods=7)
dates

DatetimeIndex(['2023-09-06 00:15:35.908882', '2023-09-07 00:15:35.908882',
               '2023-09-08 00:15:35.908882', '2023-09-09 00:15:35.908882',
               '2023-09-10 00:15:35.908882', '2023-09-11 00:15:35.908882',
               '2023-09-12 00:15:35.908882'],
              dtype='datetime64[ns]', freq='D')

In [129]:
dates = pd.date_range('2023-08-25', periods=7)
dates

DatetimeIndex(['2023-08-25', '2023-08-26', '2023-08-27', '2023-08-28',
               '2023-08-29', '2023-08-30', '2023-08-31'],
              dtype='datetime64[ns]', freq='D')

In [130]:
#Just picking the random numbers which picks value betn 0-1
M = np.random.random((7,7)) #first random is library and second random is function
M

array([[0.61148814, 0.04254226, 0.16591022, 0.24321316, 0.26341586,
        0.15186398, 0.86408778],
       [0.93396707, 0.45420284, 0.3673313 , 0.13965002, 0.74192299,
        0.08016791, 0.3660673 ],
       [0.24918971, 0.82439984, 0.1714402 , 0.02902787, 0.783743  ,
        0.34702392, 0.83368503],
       [0.48853267, 0.46348351, 0.05430468, 0.72943635, 0.40448582,
        0.28442233, 0.73729638],
       [0.17704026, 0.72110852, 0.24325891, 0.36200227, 0.1480594 ,
        0.95156126, 0.44384376],
       [0.86528536, 0.16092073, 0.914531  , 0.82646765, 0.19922332,
        0.97349108, 0.37927212],
       [0.44587842, 0.31259088, 0.73064016, 0.07231058, 0.57739831,
        0.18918208, 0.32890699]])

In [131]:
#Creating the dataframe using the randoms numbers.

df = pd.DataFrame(M, index=dates)
df

,0,1,2,3,4,5,6
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [132]:
#Changing the columns headers

df.columns = ['C1','C2','C3','C4','C5','C6','C7']
df

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [133]:
# Arranging data into ascending order in column

df.sort_values(by='C1', ascending=True)

,C1,C2,C3,C4,C5,C6,C7
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067

In [134]:
df.sort_values(by='C1', ascending=False) #False ascending execute descending ordered data.
                                        #BY index/row wise datas are always in ascending ordered.

,C1,C2,C3,C4,C5,C6,C7
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844

In [135]:
df

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [136]:
dict = {'A' : pd.Series([1, 2, 3,11], index=['a', 'b', 'c','d']),
'B' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df12 = pd.DataFrame(dict)
df12

    A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [137]:
df12.drop(['A'], axis=1) # axis=0 => rows,  axis=1 => columns
df12

    A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [138]:
#inplace works as a commit statement and it will delete that permanently.
#If we give inplace False it will bring back the column again.
# Axis= 0 is row and 1 is for column
# inplace does the delete operation.
df12.drop(['A'], axis=1, inplace=True) # axis=0 => rows,  axis=1 => columns
df12

   B
a  1
b  2
c  3
d  4

In [139]:
col1 = np.linspace(10, 100, 30)
col2 = np.random.randint(10,100,30)
df10 = pd.DataFrame({"C1" : col1 , "C2" :col2})
df10

            C1  C2
0    10.000000  46
1    13.103448  42
2    16.206897  44
3    19.310345  93
4    22.413793  22
5    25.517241  31
6    28.620690  18
7    31.724138  22
8    34.827586  53
9    37.931034  75
10   41.034483  91
11   44.137931  37
12   47.241379  26
13   50.344828  26
14   53.448276  72
15   56.551724  30
16   59.655172  54
17   62.758621  78
18   65.862069  49
19   68.965517  67
20   72.068966  54
21   75.172414  85
22   78.275862  55
23   81.379310  75
24   84.482759  70
25   87.586207  46
26   90.689655  52
27   93.793103  36
28   96.896552  66
29  100.000000  32

In [140]:
df10 = df10.drop([17,18,19], axis=0)
df10

            C1  C2
0    10.000000  46
1    13.103448  42
2    16.206897  44
3    19.310345  93
4    22.413793  22
5    25.517241  31
6    28.620690  18
7    31.724138  22
8    34.827586  53
9    37.931034  75
10   41.034483  91
11   44.137931  37
12   47.241379  26
13   50.344828  26
14   53.448276  72
15   56.551724  30
16   59.655172  54
20   72.068966  54
21   75.172414  85
22   78.275862  55
23   81.379310  75
24   84.482759  70
25   87.586207  46
26   90.689655  52
27   93.793103  36
28   96.896552  66
29  100.000000  32

In [141]:
df10 = df10.drop([16], axis=0, inplace=True)
df10

In [151]:
df10

In [172]:
df10.drop(df10.index[5], inplace=True)

AttributeError: ignored

In [153]:
df10

In [171]:
df10.iloc[10:15]

AttributeError: ignored

In [170]:
#iloc function
# iloc function use the name of row and column
#iloc function is used for integer-location based indexing,
# allowing you to select rows and columns from a DataFrame by their integer positions.
#we are trying to print column first giving 0 index
df10.iloc[10:15, 0] #for row it needs actual row id like 10 and 15 here and for column it needs index of the column.

AttributeError: ignored

In [169]:
#loc function
#loc function use the index of rows and columns
# It selects rows and columns from a DataFrame by label-based indexing.
# row_labels can be a single label, a list of labels, or a slice of labels for selecting rows.
# column_labels can be a single label, a list of labels, or a slice of labels for selecting columns.
# dataframe.loc[row_labels, column_labels]

df10.loc[10:,'C1':]

AttributeError: ignored

In [144]:
df.loc[:,:]

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [154]:
df.loc['25-08-2023':'25-08-2023','C1':'C1']

<ipython-input-154-67d2a7753ad7>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['25-08-2023':'25-08-2023','C1':'C1']

                  C1
2023-08-25  0.611488

**Reverse Diagonal**

In [155]:
df.loc['25-08-2023':'25-08-2023','C7':'C7']

<ipython-input-155-f8296650380d>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['25-08-2023':'25-08-2023','C7':'C7']

                  C7
2023-08-25  0.864088

In [156]:
df.loc['26-08-2023':'26-08-2023','C6':'C6']

<ipython-input-156-e8718737b6fc>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['26-08-2023':'26-08-2023','C6':'C6']

                  C6
2023-08-26  0.080168

In [157]:
df.loc['2023-08-27':'2023-08-27','C5':'C5']

                  C5
2023-08-27  0.783743

In [158]:
df.loc['2023-08-28':'2023-08-28','C4':'C4']

                  C4
2023-08-28  0.729436

In [159]:
df.loc['2023-08-29':'2023-08-29','C3':'C3']

                  C3
2023-08-29  0.243259

In [160]:
df.loc['2023-08-30':'2023-08-30','C2':'C2']

                  C2
2023-08-30  0.160921

In [161]:
df.loc['2023-08-31':'2023-08-31','C1':'C1']

                  C1
2023-08-31  0.445878

**Diagonal**

In [162]:
df.loc['25-08-2023':'25-08-2023','C1':'C1']

<ipython-input-162-67d2a7753ad7>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['25-08-2023':'25-08-2023','C1':'C1']

                  C1
2023-08-25  0.611488

In [163]:
df.loc['26-08-2023':'26-08-2023','C2':'C2']

<ipython-input-163-1fd126cf03ec>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['26-08-2023':'26-08-2023','C2':'C2']

                  C2
2023-08-26  0.454203

In [164]:
df.loc['27-08-2023':'27-08-2023','C3':'C3']

<ipython-input-164-0598eea2a8b0>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['27-08-2023':'27-08-2023','C3':'C3']

                 C3
2023-08-27  0.17144

In [165]:
df.loc['28-08-2023':'28-08-2023','C4':'C4']

<ipython-input-165-97a2393ef63f>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['28-08-2023':'28-08-2023','C4':'C4']

                  C4
2023-08-28  0.729436

In [166]:
df.loc['29-08-2023':'29-08-2023','C5':'C5']

<ipython-input-166-d737984eb42f>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['29-08-2023':'29-08-2023','C5':'C5']

                  C5
2023-08-29  0.148059

In [167]:
df.loc['30-08-2023':'30-08-2023','C6':'C6']

<ipython-input-167-999a0150c3ba>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['30-08-2023':'30-08-2023','C6':'C6']

                  C6
2023-08-30  0.973491

In [168]:
df.loc['31-08-2023':'31-08-2023','C7':'C7']

<ipython-input-168-acca78fa93ce>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df.loc['31-08-2023':'31-08-2023','C7':'C7']

                  C7
2023-08-31  0.328907

In [173]:
df.iloc[::] #To get all the rows and columns

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [174]:
df.iloc[3:,:]

,C1,C2,C3,C4,C5,C6,C7
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [175]:
df.iloc[:3,:]

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685

In [176]:
df.iloc[:4,:]

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296

In [177]:
df.iloc[:,3:]

                  C4        C5        C6        C7
2023-08-25  0.243213  0.263416  0.151864  0.864088
2023-08-26  0.139650  0.741923  0.080168  0.366067
2023-08-27  0.029028  0.783743  0.347024  0.833685
2023-08-28  0.729436  0.404486  0.284422  0.737296
2023-08-29  0.362002  0.148059  0.951561  0.443844
2023-08-30  0.826468  0.199223  0.973491  0.379272
2023-08-31  0.072311  0.577398  0.189182  0.328907

In [178]:
df.iloc[:,:4]

                  C1        C2        C3        C4
2023-08-25  0.611488  0.042542  0.165910  0.243213
2023-08-26  0.933967  0.454203  0.367331  0.139650
2023-08-27  0.249190  0.824400  0.171440  0.029028
2023-08-28  0.488533  0.463484  0.054305  0.729436
2023-08-29  0.177040  0.721109  0.243259  0.362002
2023-08-30  0.865285  0.160921  0.914531  0.826468
2023-08-31  0.445878  0.312591  0.730640  0.072311

In [179]:
df.iloc[:,:2]

                  C1        C2
2023-08-25  0.611488  0.042542
2023-08-26  0.933967  0.454203
2023-08-27  0.249190  0.824400
2023-08-28  0.488533  0.463484
2023-08-29  0.177040  0.721109
2023-08-30  0.865285  0.160921
2023-08-31  0.445878  0.312591

In [180]:
df.iloc[:,4:]

                  C5        C6        C7
2023-08-25  0.263416  0.151864  0.864088
2023-08-26  0.741923  0.080168  0.366067
2023-08-27  0.783743  0.347024  0.833685
2023-08-28  0.404486  0.284422  0.737296
2023-08-29  0.148059  0.951561  0.443844
2023-08-30  0.199223  0.973491  0.379272
2023-08-31  0.577398  0.189182  0.328907

In [181]:
df.iloc[3:,:]

,C1,C2,C3,C4,C5,C6,C7
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [182]:
df.iloc[::]

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [183]:
df.iloc[:1,:1]

                  C1
2023-08-25  0.611488

In [195]:
df.iloc[1:2,1:2]

                  C2
2023-08-26  0.454203

In [197]:
df.iloc[2:3,2:3]

                 C3
2023-08-27  0.17144

In [198]:
df.iloc[3:4,3:4]

                  C4
2023-08-28  0.729436

In [199]:
df.iloc[4:5,4:5]

                  C5
2023-08-29  0.148059

In [200]:
df.iloc[5:6,5:6]

                  C6
2023-08-30  0.973491

In [201]:
df.iloc[6:7,6:7]

                  C7
2023-08-31  0.328907

**REverse Diagonal**

In [203]:
df.iloc[5:6,5:6]

                  C6
2023-08-30  0.973491

In [211]:
df.iloc[::]

,C1,C2,C3,C4,C5,C6,C7
2023-08-25,0.611488,0.042542,0.165910,0.243213,0.263416,0.151864,0.864088
2023-08-26,0.933967,0.454203,0.367331,0.139650,0.741923,0.080168,0.366067
2023-08-27,0.249190,0.824400,0.171440,0.029028,0.783743,0.347024,0.833685
2023-08-28,0.488533,0.463484,0.054305,0.729436,0.404486,0.284422,0.737296
2023-08-29,0.177040,0.721109,0.243259,0.362002,0.148059,0.951561,0.443844
2023-08-30,0.865285,0.160921,0.914531,0.826468,0.199223,0.973491,0.379272
2023-08-31,0.445878,0.312591,0.730640,0.072311,0.577398,0.189182,0.328907

In [210]:
df.iloc[6:7,0:1]

                  C1
2023-08-31  0.445878

In [212]:
df.iloc[5:6,1:2]

                  C2
2023-08-30  0.160921

In [213]:
df.iloc[4:5,2:3]

                  C3
2023-08-29  0.243259

In [214]:
df.iloc[3:4,3:4]

                  C4
2023-08-28  0.729436

In [215]:
df.iloc[2:3,4:5]

                  C5
2023-08-27  0.783743

In [216]:
df.iloc[1:2,5:6]

                  C6
2023-08-26  0.080168

In [217]:
df.iloc[:1,6:7]

                  C7
2023-08-25  0.864088

In [218]:
path = '/content/Churn_Modelling.csv'
df_churn_mod = pd.read_csv(path)
df_churn_mod

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [222]:
df_churn_mod.loc['1':'1','Balance':'Balance']

    Balance
1  83807.86

In [224]:
df_churn_mod.iloc[:3,:4]

   RowNumber  CustomerId   Surname  CreditScore
0          1    15634602  Hargrave          619
1          2    15647311      Hill          608
2          3    15619304      Onio          502

In [226]:
df_churn_mod.iloc[990:,11:]

      IsActiveMember  EstimatedSalary  Exited
990                0         66214.13       0
991                1        139816.10       0
992                1        140139.28       0
993                0        102297.15       0
994                0        145765.83       0
...              ...              ...     ...
9995               0         96270.64       0
9996               1        101699.77       0
9997               1         42085.58       1
9998               0         92888.52       1
9999               0         38190.78       0

[9010 rows x 3 columns]

In [227]:
df_churn_mod.loc['9996':'9996','IsActiveMember':'IsActiveMember']

      IsActiveMember
9996               1

In [228]:
df_churn_mod.loc['9996':'9996','EstimatedSalary':'EstimatedSalary']

      EstimatedSalary
9996        101699.77

In [233]:
df_churn_mod.loc['9995':'9997','Gender':'Gender']

      Gender
9995    Male
9996    Male
9997  Female

In [236]:
df_churn_mod.iloc[9998:10000,:5]

      RowNumber  CustomerId    Surname  CreditScore Geography
9998       9999    15682355  Sabbatini          772   Germany
9999      10000    15628319     Walker          792    France

In [263]:
df_churn_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [238]:
df_churn_mod.describe() #

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [240]:
df_churn_mod.describe #It describes the data

<bound method NDFrame.describe of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]>

In [241]:
df_churn_mod.describe(include ='all') #It is taking non numeric numbers and giving values for that.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5000.50000,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [243]:
#to get the details of the data
#giving datatypes for given dataframe
df_churn_mod.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [245]:
#to get the size of the data
df_churn_mod.size
#we have 10000 rows and 14 column

140000

In [246]:
# It provides the dimensional of data
df_churn_mod.ndim

2

In [248]:
#It provides the name of the columns of the particular dataframe
df_churn_mod.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [264]:
# Giving count of each row
df_churn_mod.count()

RowNumber          10000
CustomerId         10000
Surname            10000
CreditScore        10000
Geography          10000
Gender             10000
Age                10000
Tenure             10000
Balance            10000
NumOfProducts      10000
HasCrCard          10000
IsActiveMember     10000
EstimatedSalary    10000
Exited             10000
dtype: int64

In [265]:
df_churn_mod.count

<bound method DataFrame.count of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]>

In [249]:
# Providing shape of the data
df_churn_mod.shape

(10000, 14)

In [254]:
# IT gives us statstic that how many values are null
# Following dataframe has not any null values so it is giving False value
df_churn_mod.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [258]:
df_churn_mod.isnull().sum(axis = 0)

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [261]:
df_churn_mod.sum(axis =1)

<ipython-input-261-7a548b554343>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_churn_mod.sum(axis =1)

0       15736618.88
1       15844315.44
2       15893456.37
3       15795925.63
4       15943385.92
           ...
9995    15713313.64
9996    15739522.38
9997    15637370.58
9998    15861138.83
9999    15807478.57
Length: 10000, dtype: float64

In [266]:
df_churn_mod.min()

RowNumber                 1
CustomerId         15565701
Surname               Abazu
CreditScore             350
Geography            France
Gender               Female
Age                      18
Tenure                    0
Balance                 0.0
NumOfProducts             1
HasCrCard                 0
IsActiveMember            0
EstimatedSalary       11.58
Exited                    0
dtype: object

In [267]:
df_churn_mod.max()

RowNumber              10000
CustomerId          15815690
Surname               Zuyeva
CreditScore              850
Geography              Spain
Gender                  Male
Age                       92
Tenure                    10
Balance            250898.09
NumOfProducts              4
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    199992.48
Exited                     1
dtype: object

In [268]:
df_churn_mod.sum()

RowNumber                                                   50005000
CustomerId                                              156909405694
Surname            HargraveHillOnioBoniMitchellChuBartlettObinnaH...
CreditScore                                                  6505288
Geography          FranceSpainFranceFranceSpainSpainFranceGermany...
Gender             FemaleFemaleFemaleFemaleFemaleMaleMaleFemaleMa...
Age                                                           389218
Tenure                                                         50128
Balance                                                 764858892.88
NumOfProducts                                                  15302
HasCrCard                                                       7055
IsActiveMember                                                  5151
EstimatedSalary                                        1000902398.81
Exited                                                          2037
dtype: object

In [269]:
df_churn_mod.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [270]:
df_churn_mod.CreditScore

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [271]:
df_churn_mod['CreditScore'] #We can use this way to call if our column name has space in betn.

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [272]:
df_churn_mod.CreditScore, df_churn_mod.Geography

(0       619
 1       608
 2       502
 3       699
 4       850
        ...
 9995    771
 9996    516
 9997    709
 9998    772
 9999    792
 Name: CreditScore, Length: 10000, dtype: int64,
 0        France
 1         Spain
 2        France
 3        France
 4         Spain
          ...
 9995     France
 9996     France
 9997     France
 9998    Germany
 9999     France
 Name: Geography, Length: 10000, dtype: object)

In [274]:
df_churn_mod[['CustomerId', 'Surname']]

      CustomerId    Surname
0       15634602   Hargrave
1       15647311       Hill
2       15619304       Onio
3       15701354       Boni
4       15737888   Mitchell
...          ...        ...
9995    15606229   Obijiaku
9996    15569892  Johnstone
9997    15584532        Liu
9998    15682355  Sabbatini
9999    15628319     Walker

[10000 rows x 2 columns]

In [275]:
df_churn_mod[['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography']]

      RowNumber  CustomerId    Surname  CreditScore Geography
0             1    15634602   Hargrave          619    France
1             2    15647311       Hill          608     Spain
2             3    15619304       Onio          502    France
3             4    15701354       Boni          699    France
4             5    15737888   Mitchell          850     Spain
...         ...         ...        ...          ...       ...
9995       9996    15606229   Obijiaku          771    France
9996       9997    15569892  Johnstone          516    France
9997       9998    15584532        Liu          709    France
9998       9999    15682355  Sabbatini          772   Germany
9999      10000    15628319     Walker          792    France

[10000 rows x 5 columns]

In [276]:
df_churn_mod.CreditScore, df_churn_mod.Surname, df_churn_mod.CustomerId

(0       619
 1       608
 2       502
 3       699
 4       850
        ...
 9995    771
 9996    516
 9997    709
 9998    772
 9999    792
 Name: CreditScore, Length: 10000, dtype: int64,
 0        Hargrave
 1            Hill
 2            Onio
 3            Boni
 4        Mitchell
           ...
 9995     Obijiaku
 9996    Johnstone
 9997          Liu
 9998    Sabbatini
 9999       Walker
 Name: Surname, Length: 10000, dtype: object,
 0       15634602
 1       15647311
 2       15619304
 3       15701354
 4       15737888
           ...
 9995    15606229
 9996    15569892
 9997    15584532
 9998    15682355
 9999    15628319
 Name: CustomerId, Length: 10000, dtype: int64)

#**Data Selection Based on Condition**

In [ ]:
df_churn_mod[df_churn_mod.Gender == 'Male']

In [280]:
df_churn_mod[(df_churn_mod.Gender == 'Male') & (df_churn_mod.Age >= 45)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9953,9954,15655952,Burke,550,France,Male,47,2,0.00,2,1,1,97057.28,0
9954,9955,15739850,Trentino,645,France,Male,45,6,155417.61,1,0,1,3449.22,0
9967,9968,15603794,Pugliesi,623,France,Male,48,5,118469.38,1,1,1,158590.25,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0

In [282]:
df_churn_mod[(df_churn_mod.Gender == 'Male') & (df_churn_mod.Age >= 45) & (df_churn_mod.Balance >= 100000)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
56,57,15630053,Tsao,656,France,Male,45,5,127864.40,1,1,0,87107.57,0
70,71,15703793,Konovalova,738,Germany,Male,58,2,133745.44,4,1,0,28373.86,1
91,92,15731511,Ritchie,808,France,Male,45,7,118626.55,2,1,0,147132.46,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9917,9918,15755731,Davis,635,Germany,Male,53,8,117005.55,1,0,1,123646.57,1
9954,9955,15739850,Trentino,645,France,Male,45,6,155417.61,1,0,1,3449.22,0
9967,9968,15603794,Pugliesi,623,France,Male,48,5,118469.38,1,1,1,158590.25,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0

In [284]:
df_churn_mod[(df_churn_mod.Gender == 'Male') | (df_churn_mod.Age >= 45) | (df_churn_mod.Balance >= 100000)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [285]:
df_churn_mod[(df_churn_mod.Geography == 'France') | (df_churn_mod.CreditScore >= 400)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [290]:
df_churn_mod[(df_churn_mod.Geography == 'Germany') ^ (df_churn_mod.CreditScore >= 400)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [294]:
df_churn_mod[(df_churn_mod.Geography == 'Germany') & (df_churn_mod.Surname == 'Young') & (df_churn_mod.CreditScore >= 400)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
339,340,15807923,Young,716,Germany,Female,39,10,115301.31,1,1,0,43527.40,1
5378,5379,15720968,Young,606,Germany,Male,27,2,130274.26,2,1,0,147533.09,0

In [293]:
df_churn_mod[(df_churn_mod.Surname == 'Young')]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
339,340,15807923,Young,716,Germany,Female,39,10,115301.31,1,1,0,43527.40,1
791,792,15643696,Young,611,France,Male,49,3,0.00,2,1,1,142917.54,0
1416,1417,15667651,Young,585,Spain,Female,33,8,0.00,2,1,0,114182.07,0
2742,2743,15576126,Young,649,France,Female,41,2,125785.23,1,1,1,70523.92,0
2836,2837,15768455,Young,679,France,Male,60,8,0.00,2,1,1,51380.90,0
4758,4759,15601263,Young,493,Spain,Female,48,7,0.00,2,1,0,48545.10,0
5132,5133,15579826,Young,439,France,Female,66,9,0.00,1,1,0,65535.56,0
5298,5299,15794187,Young,695,France,Male,36,6,114007.50,2,1,0,118120.88,0
5378,5379,15720968,Young,606,Germany,Male,27,2,130274.26,2,1,0,147533.09,0
5445,5446,15779174,Young,451,France,Female,36,2,0.00,2,1,1,180142.42,0
5485,5486,15753837,Young,573,Spain,Male,38,4,0.00,2,1,1,196517.43,0
6313,6314,15812482,Young,575,France,Male,27,3,139301.68,1,1,0,99843.98,0
8100,8101,15631217,Young,663,France,Male,40,6,156218.19,1,0,1,33607.72,0
8308,8309,15719898,Young,556,France,Male,36,7,154872.08,2,1,1,32044.64,0
8611,8612,15617029,Young,596,Spain,Female,30,1,0.00,2,1,0,8125.39,0
8790,8791,15691792,Young,416,Spain,Male,35,8,0.00,1,0,0,119712.78,0
9657,9658,15740043,Young,606,France,Male,32,5,83161.65,1,1,1,116885.59,0
9732,9733,15622192,Young,724,Spain,Male,39,3,0.00,2,0,1,95562.81,0
9872,9873,15648032,Young,588,Spain,Male,37,2,0.00,2,0,1,187816.59,0

In [297]:
df_churn_mod.Surname.unique()

array(['Hargrave', 'Hill', 'Onio', ..., 'Kashiwagi', 'Aldridge',
       'Burbidge'], dtype=object)

In [308]:
df_churn_mod[(df_churn_mod['Geography'].isin (['France','Germany']) & (df_churn_mod.Gender == 'Male'))]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1